[package]
name = "mfping"
version = "0.1.0"
edition = "2021"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.tokio]
version = "1.27"
features = ["full"]

[dependencies]
serde_json = "1.0"
reqwest = "0.11"
